var services=angular.module('services', [])
    services.factory('Meals', function () {
        // Might use a resource here that returns a JSON array
        var items = [{index:   1 ,kind:  1,kindex: 21 ,color:"#FCD2AB"  , name:"    Red Pottery Tripod Bow  ", period:" Neolithic Age (ca. 8000-2000 BCE)       ", type:"   proto-porcelain         ", kiln:"       ", intro:"  Formed by the coil method, this bowl is a typical type among the Cishan assemblage. The coil method is one of the most ancient ways to make pottery. First the clay is rolled into a cord, then the cord of clay is wound around into the basic vessel shape, which is then smoothed and pressed together with watery clay. The irregular shape and uneven wall thickness is characteristic of this method. ", url:"    ./img/01.png    "},
                    {index: 2   ,kind: 1 ,kindex:3  ,color:"#7F6858"  , name:"    Double-handled Painted Pottery Pot with Whorl, Diamond, and Geometric Patterns  ", period:" Neolithic Age (ca. 8000-2000 BCE)       ", type:"   proto-porcelain         ", kiln:"       ", intro:"  Painted pottery appeared more than 6,000 years ago based on the red pottery tradition of the Yellow River valley. It began first in the east and subsequently spread west. This vessel belongs to the Banshan type of the Majiayao culture, 2600-2300 BCE. Banshan pottery is characteristically two tones with alternating red and black painted patterns, with cross-hatching filling in small areas. ", url:"    ./img/02.png    "},
                    {index: 3   ,kind: 1 ,kindex: 10 ,color:"#754C2F"  , name:"    Red Pottery Gui Vessel  ", period:" Neolithic Age (ca. 8000-2000 BCE)       ", type:"   proto-porcelain         ", kiln:"       ", intro:"  A gui is type of water vessel shape like a bird. The type first appeared in the Shandong region. Shandong, located in the east, was at that time inhabited by the Shaohao and Taihao tribes, who used the bird as a totem. Longshan is one of the Late Neolithic cultures of China. It was named after Longshan village, Zhangqiu county, Shandong province where is was first recognized in 1928.  ", url:"    ./img/03.png    "},
                {index: 4   ,kind:  1,kindex: 36 ,color:"#CEB7A5"  , name:"    White Pottery Pot with Carved Taotie Pattern and Double Rings   ", period:" Shang dynasty (ca. 1600-1028 BCE)       ", type:"   proto-porcelain         ", kiln:"       ", intro:"  Taotie is a mythical carnivorous monster. Bronzes in the Shang and Zhou dynasties commonly used the head of these creature in decorations, which is known as the taotie pattern. Use of 'taotie' to name this motif began with a book, Xuanhe bogutu, written in the 12th century of the Song dynasty (960-1279). By the Shang dynasty, due to increases in kiln temperature and finer clays, the fabric of white ceramics became finer and whiter. The elaborate carving techniques show the high level of development of late Shang white ceramics.   ", url:"    ./img/04.png    "},
                {index: 5   ,kind:  1,kindex: 17 ,color:"#D8C9A5"  , name:"    Celadon Jiaodou Tripod Bowl ", period:" Warring States Period (475-222 BCE)         ", type:"   proto-porcelain         ", kiln:"       ", intro:"  The jiaodou, or diaodou, was popular during the Han to Jin period (third century BCE to fifth century CE). It was usually on the hearth, with charcoal to keep it warm. During journeys it was carried as a heating vessel to warm food. It was commonly used on military expeditions. A Tang dynasty poem famously describes this vessel type: 'The journeying people with tripod bowls (diaodou) in dark and windy weather'.  ", url:"    ./img/05.png    "},
                {index: 6   ,kind: 1 ,kindex: 5 ,color:"#C5A7B8"  , name:"    Color-painted Pottery Pot with Dragon and Phoenix Designs in Relief ", period:" Western Han dynasty (206 BCE – 8 CE)        ", type:"   proto-porcelain         ", kiln:"       ", intro:"  Painted pottery began from the Late Neolithic period about 5,000 years ago. Typically, such pottery vessels are painted with red, white, yellow, brown, and black directly on the grey ceramic surface, or on a white or tan slip. To reach colourful effect, this vessel is applied with many colors including red, green, blue and black, white and yellow. The elaborate pattern remains vibrant after more than 2,000 years.    ", url:"    ./img/06.png    "},
                {index: 7   ,kind:  1,kindex: 6 ,color:"#174127"  , name:"    Green-glazed Pottery Pot with Animal-mask Ears  ", period:" Eastern Han dynasty (25-220)        ", type:"   green glaze     ", kiln:"       ", intro:"  The low-temperature lead green glaze over the entire body of the pot is also known as the 'melon skin green'. In China, low-temperature lead glaze was invented much later than the blue-green celadon glaze. The lead glaze has a more polished, smooth surface and the glaze layer is pure and transparent like glass. However, it is easily scratched, and its chemical stability is low.    ", url:"    ./img/07.png    "},
                {index: 8   ,kind:1  ,kindex: 4 ,color:"#6F6849"  , name:"    Celadon Granary with Modeled Figurines  ", period:" Three Kingdoms (220-265)        ", type:"   celadon         ", kiln:"       ", intro:"  This granary uses the motifs of a hundred birds feeding, people celebrating harvest, and a full complement of livestock, all expressing the ideals of farm life in the Yangtse delta region of 1,700 years ago. It was unearthed from a burial datable to the Three Kingdoms (220-265) in Shaoxing, Zhejiang province, in the late 1930s. Burial objects (ming qi) were used to ensure the deceased could maintain enjoyment after death.   ", url:"    ./img/08.png    "},
                {index: 9   ,kind:3  ,kindex: 1 ,color:"#6B6752"  , name:"    Celadon Sheep   ", period:" Western Jin dynasty (265-316)       ", type:"   celadon         ", kiln:"       ", intro:"    In ancient times, sheep were regarded as auspicious. Sheep-shaped ceramics, which were popular from the Three Kingdoms period (220-265) to the Jin dynasty (265-420), are very delicate and charming. ", url:"    ./img/09.png    "},
                {index: 10  ,kind: 4 ,kindex: 1 ,color:"#94A999"  , name:"    Celadon Wine Vessel with Lotus Decoration   ", period:" Northern Dynasties (386-581)        ", type:"   blue glaze      ", kiln:"       ", intro:"  The wine vessel has a slightly flared mouth, long neck, bulging body and high foot ring. There are six bands around the shoulders and neck and altogether 11 tiers of decoration on the whole vessel. The three tiers of decoration on the neck are those of celestials, rosette and animal-mask designs and coiled dragons separated by bands of bowstring design. The principal part of the decoration on the body is formed by six tiers of designs of inverted and non-inverted lotus petals. The base is also decorated with two tiers of lotus petals. A bluish green glaze covers the whole vessel. The inside of the deep foot ring is not glazed. The vessel is one of the four wine vessels with lotus decoration unearthed from the Feng tomb in Jingxian County, Hebei Province. The ornate decoration on this large and magnificently shaped vessel is created by combining the appliquéd, impressed, embossed, incised, molded and relief methods. The designs of lotus petals, rosettes and celestials reflect the influence of Buddhist art on the northern ceramics. Analysis of the paste and glaze of this representative piece of northern celadon shows that it is a characteristic and outstanding example of northern celadon ware.  ", url:"    ./img/10.png    "},
                {index: 11  ,kind: 1 ,kindex: 16 ,color:"#DEE0D8"  , name:"    White-glazed Jar    ", period:" Sui dynasty (581-618)       ", type:"   white glaze     ", kiln:"       ", intro:"  White porcelain succeeded in the Sui dynasty, although its emergence can be traced back to the Northern dynasty (386-534). Compared to those of the Northern dynasty, the white porcelain technique during the Sui dynasty showed important progress: the quality of glaze improved, and the early flaws such as yellow or green color within white porcelain disappeared.  ", url:"    ./img/11.png    "},
                {index: 12  ,kind:1,kindex:  12,color:"#BFCFCF"  , name:"    Celadon Octagonal Vase  ", period:" Tang dynasty (618-907)      ", type:"   blue glaze      ", kiln:"   Yue Kiln    ", intro:"  This is a water vessel for washing hands. The Yue kiln in the Tang period had a huge scale of porcelain production for its products were very popular. Yue wares were praised as 'jade' and 'ice' and the Yue kiln was regarded as the top amongst the Tang dynasty kilns. There are 14 pieces of Yue celadon wares unearthed in 1987 from the tomb of Famen temple at Fufeng of Shaanxi province. The inscription on a stele describes them as of 'mysterious porcelain color'. One of them was identical to this vase.    ", url:"    ./img/12.png    "},
                {index: 13  ,kind: 1 ,kindex: 18 ,color:"#D8D7D2"  , name:"    White-glazed Bowl with Disk-shaped Bottom   ", period:" Tang dynasty (618-907)      ", type:"   white glaze     ", kiln:"    Xing kilns     ", intro:"  Bowl with disk-shaped bottom is a typical product of Xing kiln in the Tang dynasty. This shape of bowl appeared from the Tang dynasty, and was named after the base that has the shape of a jade disk. This type of bowls was widely made in kilns across China as a novel food container. The center of the Xing kiln complex was located in Neiqiu and Lincheng counties in Hebei province under Xingzhou region in Tang dynasty. Xing kiln's white porcelain has a very fine body applied with pure white glaze, and used to be reserved for the imperial family in the Tang dynasty.    ", url:"    ./img/13.png    "},
                {index: 14  ,kind: 5 ,kindex: 1 ,color:"#CEC49A"  , name:"    Tricolor Pottery Figurine of the Heavenly King  ", period:"  Tang dynasty (618-907)         ", type:"   celadon         ", kiln:"       ", intro:"  The Heavenly King is one of the figurines comprising the burial assemblages during the Tang dynasty. Together with the guardian beasts, the Heavenly King, usually in pair, were placed in front of the tomb path or the chamber, behind the guardian beasts. Collectively they were called the 'four deities' in extant ancient records.   ", url:"    ./img/14.png    "},
                {index: 15  ,kind:1  ,kindex: 1 ,color:"#DF9E61"  , name:"    Tripod Incense Burner with Marbleized Clay  ", period:"  Tang dynasty (618-907)         ", type:"    clay       ", kiln:"   Gongyi kilns    ", intro:"  Gongyi kiln site is located inat Gongyi city, Henan province The incense burner was made with twisted clays of two colors. The irregular flower pattern is a natural result from the twist. This is a rare masterpiece of marbleized wares. Tripod pot was a common type from Gongyi kiln in Henan province. It is an imitation of the Tang dynasty metal ware and often made into tricolor wares.  ", url:"./img/15.png"},
                {index: 16  ,kind: 5 ,kindex: 2 ,color:"#6C3631"  , name:"    Tricolor Pottery Horse  ", period:" Tang dynasty (618-907)      ", type:"celadon", kiln:"       ", intro:"  The horse was attached with great importance in the Tang dynasty, which was related to the nomadic lineage of the Li imperial family. Tang Taizong (Li Shimin, r. 627-649) had the artist Yan Liben (ca. 600-673) draw six horses to be carved in relief on stone tablets to decorate his own mausoleum, the Zhaoling Tomb. Tang Xuanzong (Li Longji, r. 712-756) trained horses to gallop in rhythm on his birthday. The many tricolor pottery horses excavated from tombs datable to the Tang dynasty reflect their fondness of horse.    ", url:"    ./img/16.png    "},
                {index: 17  ,kind: 1 ,kindex: 24 ,color:"#A89E7F"  , name:"    Celadon Plate with the Mouth in the Shape of a Water-chestnut Flower    ", period:" Five Dynasties (907-960)        ", type:"   celadon         ", kiln:"   Yue Kiln    ", intro:"  Yue kiln is located insite at Cixi, Zhejiang province. Porcelain ware of the Five Dynasties was influenced by the design of gold and silver ware. Plates were usually made with flower shaped mouths, and vases were often shaped after the melon. This plate shows clear signs of wear and tear, which indicates that it has won fondness of many people.  ", url:"    ./img/17.png    "},
                {index: 18  ,kind: 3 ,kindex: 6 ,color:"#A6BBCD"  , name:"    Light-sky-blue Glazed Zun Container with Bowstring Pattern  ", period:" Song dynasty (960-1279)     ", type:"   sky-blue glaze      ", kiln:"   Ru kiln     ", intro:"  Ru Kiln is located in Qingliangsi, Baofeng county, Henan province. This container is shaped like a Han dynasty bronze zun. It has three legs and a flat bottom. The diameter of the mouth is nearly the same as that of the bottom. Raised bowstring lines decorate the top, the middle and the bottom of the container. On the bottom of the container are five spur marks. The spurs were used to support the porcelain ware during firing.       ", url:"    ./img/18.png    "},
                {index: 19  ,kind:1,kindex: 15 ,color:"#AEBFCB"  , name:"    Celadon Vase with Bowstring Decoration  ", period:" Song dynasty (960-1279)     ", type:"   celadon         ", kiln:"   Guan Ware   ", intro:"   The zun container has a delicate sky-blue glaze both inside and out. Tiny cracks found over its fine smooth surface are a prized characteristic.   ", url:"    ./img/19.png    "},
                {index: 20  ,kind:1  ,kindex: 2 ,color:"#9E988B"  , name:"    Celadon Incense Burner with Two Fish-shaped Handles ", period:" Song dynasty (960-1279)     ", type:"   celadon         ", kiln:"   Ge kilns    ", intro:"  This burner imitates the shape of a bronze gui vessel (a food container without cover or handle), which is an ceremonial object that appeared in the Shang and Zhou dynasties (16th century BCE-221 BCE). This simple and elegant object has two symmetrical fish-shaped handles, a foot ring, and an S-shaped body with contracting mouth and round belly. The body is covered with lighter blue glaze with a crackle pattern called 'gold threads and iron lines', which enhances the porcelain. On the bottom are six round spur-marks.      ", url:"    ./img/20.png    "},
                {index: 21  ,kind: 2 ,kindex: 13 ,color:"#CBBEC3"  , name:"    White-glazed Boy-shaped Pillow  ", period:"  Song dynasty (960-1279)        ", type:"   white glaze     ", kiln:"    Ding kilns     ", intro:"    This incense burner is one of the finest porcelains from the Ge kiln of the Song dynasty (960-1279). Although many imitations were created in the Yuan and Ming dynasties (1271-1644), none can compare with this masterpiece. The Qianlong Emperor (r. 1736-1795) treasured this burner. He composed a poem for it in the spring of 1776 and ordered it carved on the bottom of the burner.  ", url:"    ./img/21.png    "},
                {index: 22  ,kind: 1 ,kindex: 9 ,color:"#73879A"  , name:"    Moon-white Glazed Zun Vessel with Vertical Ridges   ", period:" Northern Song dynasty (960-1127)        ", type:"           ", kiln:"    Jun kiln   ", intro:"  Jun kiln is located in Yuzhou, Henan province This is a typical porcelain ware for display in the Song court. Most surviving vessels from Song dynasty Jun kiln are flowerpots and flowerpot stands, very few are zun vessels with vertical ridges, approximately 10 in total worldwide. Besides the one displayed here in the Palace Museum collection, the rest are in the collection of Shanghai Museum and the National Palace Museum in Taibei.    ", url:"    ./img/22.png    "},
                {index: 23  ,kind:  2,kindex:6,color:"#A7BDB6"  , name:"    Celadon Vase with Bowstring Patterns and Tube-shaped Ears,  ", period:" Southern Song dynasty (1127-1279)       ", type:"   blue glaze      ", kiln:"    Longquan Ware  ", intro:"  Longquan kiln is located in Longquan, Zhejiang province. The vase was designed after a bronze pot of ancient times. With archaic and elegant style, it is a masterpiece of Longquan celadon wares.  ", url:"    ./img/23.png    "},
                {index: 24  ,kind: 1 ,kindex: 31 ,color:"#BFB4A4"  , name:"    Bluish-white Glazed Ewer and Warming Bowl with Carved Floral Design ", period:"  Song dynasty (960-1279)        ", type:"   blue-and-white      ", kiln:"   Jingdezhen Ware ", intro:"  The warming bowl is filled with hot water to warm wine contained in the ewer. This kind of wine set can be found in paintings datable to the early period of the Five Dynasties (907-960). According to the excavated wine vessels and the Song dynasty archive, ewer and warming bowl were widely used in the Northern Song dynasty (960-1127).    ", url:"    ./img/24.png    "},
                {index: 25  ,kind: 2 ,kindex:  14,color:"#726A6F"  ,name:"    Pillow with Black Lion Design on a White Ground, Inciseded with Two Chinese Characters for 'Protecting the House' (Zhen Zhai)   ", period:" Song dynasty (960-1279)         ", type:" black and white", kiln:"   Cizhou kiln     ", intro:"  Cizhou kiln is located in Handan, Hebei province. Porcelain pillows decorated with beasts, such as lion and tiger, were designed to express people's wish for peace and good luck. Besides, those made in Cizhou kiln were also painted with children at play, fish and weed, bird and flower as decoration.    ", url:"    ./img/25.png    "},
                {index: 26 ,kind:  1 ,kindex: 7 ,color:"#AEA596"  , name:"    Jar with Carved Floral Design   ", period:" Song dynasty (960-1279)         ", type:"   black glaze      ", kiln:"   Dangyangyu kiln     ", intro:"  Dangyangyu kiln is located in Xiuwu county, Henan province The decoration of this jar is very special: A layer of decoration clay was applied to the biscuit of the jar before the craftsman carved floral motifs on the clay layer and removed the rest to expose the grey biscuit. In so doing, the result jar would show white floral design on a dark ground. In Song and Jurchen Jin (1115-1234) dynasties, many kilns in Shanxi, Hebei, and Henan provinces adopted such kind of decoration style. Among them, the Dangyangyu kiln in Henan province made the best products.  ", url:"    ./img/26.png    "},
                {index: 27 ,kind:  1 ,kindex: 22 ,color:"#243139"  , name:"    Black-glazed Small Cup with Design of Rabbit Hair Streaks   ", period:" Song dynasty (960-1279)         ", type:"  black glaze         ", kiln:"   Jian kiln   ", intro:"  Jian kiln is located in Shuiji town, Jianyang, Fujian province The thin brown or iron rust colored strips on black-glazed porcelain wares of the Song dynasty is called 'rabbit hair streak' patterns for their similarity to hare's fur. Fujian province is celebrated for the production of black-glazed small cups with design of rabbit hair streaks, with those produced in Jian kiln the best acclaimed. At the time, many literati praised the product in their works.   ", url:"    ./img/27.png    "},
                {index: 28 ,kind:  2 ,kindex:  10,color:"#924889"  , name:"    Mallow-shaped Flowerpot with Rose-purple Glaze  ", period:" Song dynasty (960-1279)         ", type:"   purple glaze        ", kiln:"   Jun kiln    ", intro:"  In the form of a mallow blossom with six petals, this flowerpot has a trumpet mouth with emphatic rim, large stomach, and a foot ring. Both the interior and the rim of the mouth are glazed light blue, while the exterior is rose purple. The edges of the mouth and foot are covered with a thin brown glaze.   The foot has five draining holes, and the number seven (qi) indicating the size of the flowerpot. The Qing artist also carved on the foot two inscriptions reading 'Palace of Established Happiness [Jianfu gong]' and 'use among bamboo, stones and rockeries,' which suggests its function and place of use.  ", url:"    ./img/28.png    "},
                {index: 29 ,kind:  1 ,kindex: 20 ,color:"#282017"  , name:"    Bowl with Applied Papercut Plum Blossom Design  ", period:" Song dynasty (960-1279)         ", type:"      brown glaze     ", kiln:"   Jizhou kiln     ", intro:"  Jizhou kiln is located in Ji'an, Jiangxi province. Exemplifying the Song dynasty porcelain wares, this bowl integrates multiple decoration techniques--the papercut floral design in the well, rabbit-hair-streak glaze in interior wall, and tortoise-shell glaze in exterior wall. However, the most notable decoration is the plum blossom in the center of the bowl well.   ", url:"    ./img/29.png    "},
                {index: 30 ,kind:  1 ,kindex: 14 ,color:"#101211"  , name:"    Black-glazed Vase Carved with Floral Design ", period:" Western Xia dynasty (1038-1227)         ", type:"    black glaze        ", kiln:"   Lingwu kiln ", intro:"  Lingwu kiln is located in Lingwu, Ningxia Hui Autonomous Region. By comparison, historians found the clay and glaze of this vessel similar to the excavated Lingwu wares in Ningxia Hui Autonomous Region in terms of the clay body and the glaze type. Therefore, this vase is considered a Lingwu ware. Sharing the same glaze colors and subject matters of the motif, porcelain wares of the Western Xia dynasty were deeply affected by the style of Cizhou wares in Hebei province. However, Lingwu wares look strong and wild, reflecting the ethnic characteristics.    ", url:"    ./img/30.png    "},
                {index: 31 ,kind:  2 ,kindex: 15 ,color:"#E1AD6B"  , name:"    Painted Tiger-shaped Pillow ", period:" Jin dynasty (1115-1234)         ", type:"   brown glaze        ", kiln:"   Changzhi kiln   ", intro:"  Tiger-shaped pillows of this type were mainly produced by Cizhou kiln in Hebei province, Bacun kiln in Yu county of Henan province, and Changzhi kiln in Shangxi province of north China. The tiger's head either faces left or right; the glaze are either in light yellow or darker; the pillow top is usually in oval shape. This ware is believed to date to the Jin dynasty because of a similar pillow kept by the Shanghai Museum, on the bottom of which is inscribed with the reign mark of the Dading era of the Jin dynasty. ", url:"    ./img/31.png    "},
                {index: 32 ,kind:  1 ,kindex: 23 ,color:"#8FA3B7"  , name:"    Blue-and-white Plate with Designs of Qilin Unicorn and Flying Phoenix   ", period:" Yuan dynasty (1271-1368)        ", type:"   blue-and-white      ", kiln:"   Jingdezhen kilns    ", intro:"  The design of a Qilin (or kyrin) and a flying phoenix painted in the center of the plate symbolizes auspiciousness and harmony.   In the Yuan dynasty, there were two ways to make blue-and-white porcelain wares: one was to paint the design with cobalt blue pigment on the white clay body; the other was to leave the design intact but instead paint the rest part of the white clay body with cobalt blue pigment, so that the result porcelain ware showed white design on a blue ground, such as the plate displayed here. ", url:"    ./img/32.png    "},
                {index: 33 ,kind:  2 ,kindex:  8,color:"#4E6893"  , name:"    Blue-and-white Covered Jar with Underglaze-red Patterns in Open Work    ", period:" Yuan dynasty (1271-1368)        ", type:"     blue-and-white       ", kiln:"   Jingdezhen kilns    ", intro:"  The jar has a straight mouth, a short neck, a swollen stomach, and an unglazed foot ring. The knob on the cover is in the form of a squatting lion, below which is painted a blue-and-white circular design that includes lotus, tendrils, and meandering patterns. The mouth rim and the lower part of the stomach have interlocking flowers and tendrils. The shoulder is covered with a design of cloud-shaped heads of ruyi scepters, in which white lotus grow out of ripples. Between the ruyi scepters are interlocking peony blossoms. The stomach has four rhombic framed panels displaying various landscapes of the four seasons. Carved in low relief, the rocks and flowers use underglaze red. Above the foot ring are more tendrils and stylized lotus. With a swollen shape and distinct design, the jar combines diverse techniques including painting, engraving, sculpting, and applique. The blue and underglaze red complement each other.   Blue-and-white glaze with patterns in underglaze red was an innovation of the Yuan dynasty. The blue is attributed to cobalt oxide (CoO), which manifests a stable color. The underglaze red is copper hemioxide (Cu2O) that is volatile. Thus, the combination of two materials with contradictory properties requires a perfect oxygen atmosphere. Wares with underglaze colors reveal sophisticated techniques of the Yuan dynasty.   The blue-and-white jar with patterns in underglaze red is one of two similar containers unearthed from a Yuan dynasty kiln in Baoding, Hebei Province in 1965. ", url:"    ./img/33.png    "},
                {index: 34 ,kind:  1 ,kindex: 28 ,color:"#9B4626"  , name:"    Red-glazed Ewer with Carved Design of Dragon among Clouds   ", period:" Yuan dynasty (1271-1368)        ", type:"   red glaze       ", kiln:"   Jingdezhen kilns    ", intro:"  The glaze is evenly applied and shows rich and bright red color. Exemplifying the Yuan dynasty dragon images, the dragons portrayed on the ewer have thin necks and long snouts. This pear-shaped ewer was a new type created in Jingdezhen in the Yuan dynasty. The elegantly small size indicates that it should be a piece of tableware. ", url:"    ./img/34.png    "},
                {index: 35  ,kind:1 ,kindex:  25,color:"#232E7E"  , name:"    Blue-glazed Yi Ewer with Patterns of Flowers and Clouds in Gold ", period:" Yuan dynasty (1271-1368)        ", type:"   blue glaze      ", kiln:"   Jingdezhen kilns    ", intro:"  This ware imitates the ancient bronze prototype. The blue glazed is as lustrous as sapphire, and is brightly shiny with the gold paint. The yiewer was unearthed from a cellar in Baoding, Hebei province in 1964, along with blue-glazed small cups and dishes with gold motifs.   ", url:"    ./img/35.png    "},
                {index: 36  ,kind: 2 ,kindex: 4 ,color:"#9FA98C"  , name:"    Celadon Washer Applied with Four Molded Fish    ", period:" Yuan dynasty (1271-1368)        ", type:"   blue glaze         ", kiln:"    Longquan kiln  ", intro:"  Longquan kiln is located in Longquan, Zhejiang province. When the washer is filled with water, the four fish seem swimming freely in a pond. Located in Longquan county of Zhejiang province, the Longquan kiln was the largest non-official kiln complex in south China during the Song (960-1279) and Yuan dynasties. Longquan wares were exported to many countries including Japan, the Philippines, Malaysia, Pakistan, India, and Egypt. Here is a case in point: Among some 17,000 porcelain wares datable to the Yuan dynasty recovered from a sunken vessel under the sea of South Korean in 1976, more than 9,000 were Longquan wares.    ", url:"    ./img/36.png    "},
                {index: 37  ,kind: 1 ,kindex: 13 ,color:"#A8C3C2"  , name:"    Covered Sky-blue Prunus Vase with Purple-red Splashes   ", period:" Yuan dynasty (1271-1368)        ", type:"    sky-blue       ", kiln:"   Jun kiln    ", intro:"  Jun kiln site ais located int Yuzhou city, Henan province This vase bears purple-red spots on its moon-white glaze, like clouds floating in the sky. The craftsman did it randomly but somehow achieved a very artistic style. Originally used as a wine container, the prunus vase was designed with a cover. However, as time went by, most of those vases lost their covers. Among the very few surviving prunus vases from the Jun kiln, this one with its cover intact is very precious.   ", url:"    ./img/37.png    "},
                {index: 38  ,kind: 1 ,kindex: 8 ,color:"#422422"  , name:"    Four-handled Vase with Design of Phoenix among Clouds on a White Ground ", period:" Yuan dynasty (1271-1368)        ", type:"   blue-and-white        ", kiln:"   Cizhou kiln     ", intro:"  Cizhou kiln is located in Handan, Hebei province In the Yuan dynasty, the Cizhou kiln mainly produced white glazed wares with black motifs, characterized with big size and thick bodies. Big basins, big jars, and pillows were major products. Dragon among clouds, phoenix among clouds, wild goose among clouds, and fish and grass were popular decoration patterns.   ", url:"    ./img/38.png    "},
                {index: 39 ,kind:   1,kindex: 29 ,color:"#989FB3"  , name:"    Blue-and-white Ewer with Floral Design  ", period:" Hongwu reign (1368-1398), Ming dynasty (1368-1644)      ", type:"     blue-and-white      ", kiln:"   Cizhou kiln     ", intro:"  Ewers are liquor vessels derived from water droppers (zhu zi). Those dating to the Ming dynasty frequently possess long tapered necks, curved spouts, and bent handles. The ewer exhibited here dates to the Hongwu reign, an outstanding example of Ming dynasty blue-and-white porcelain. Chrysanthemum and camellia flowers decorating the ewer were popular designs at that time.   ", url:"./img/39.png"},
                {index: 40 ,kind:  3 ,kindex: 10 ,color:"#9B9EA2"  , name:"    Melon-shaped Underglaze-red Jar with Designs of Flowers of the Four Seasons ", period:" Hongwu reign (1368-1398), Ming dynasty (1368-1644)      ", type:"   Underglaze-red      ", kiln:"   Jingdezhen kilns    ", intro:"  In Chinese ceramic terminology, this type of red porcelain ware is referred to as 'underglaze red' (youli hong) because the red color, rich in copper oxide, was painted beneath the transparent glaze layer. In contrast with the white background, the red color is extremely bright and therefore was thought to create a very auspicious atmosphere. The melon veins starts from the very bottom to the mouth rim of the jar. Around the stomach of the jar are painted twelve sets of flowers of four seasons with lake rocks. Tall and large, the jar is densely decorated with varied floral motifs in clear arrangement. It reflects the free and unconstraint style in artistic representation during the transitional period from late Yuan (1271-1368) to early Ming dynasty.    ", url:"    ./img/40.png    "},
                {index: 41 ,kind:  1 ,kindex: 19 ,color:"#9DBBEE"  , name:"    Blue-and-white Bowl with the Design of Nine Dragons Frolicing in the Sea    ", period:" Chenghua reign (1465-1487), Ming dynasty(1368-1644)     ", type:"   Blue-and-white      ", kiln:"   Jingdezhen kilns    ", intro:"  Dragon was worshiped and revered by Chinese people as a divine beast. The legend has it that four Dragon Kings governing the seas of four directions lived in the undersea Crystal Palaces. Therefore, the design of dragon among waves is a common decorative motif. The nine dragons painted in cobalt blue on the bowl's exterior wall create an impressive view. The blue-and-white porcelain wares dating to the Chenghua reign are well known for light blue colors. The result blue color shows different tones that implementing each other well, augmenting the vigor of the dragons.  ", url:"    ./img/41.png    "},
                {index: 42 ,kind:  3 ,kindex: 8 ,color:"#848685"  ,name:"    Covered Jar with Polychrome Design of Carp and Weed ", period:" Jiajing reign (1522-1566), Ming dynasty (1368-1644)         ", type:"      blue-and-white     ", kiln:"   Jingdezhen kilns    ", intro:"  Fish with weeds are Chinese people's favorite decorative design, for the Chinese word for 'fish' (yu) is a homophone of that for 'abundance' (yu). The carp with clearly painted scales and fins swimming amidst lotuses, duckweed, and weeds are vividly presented in polychrome colors over the glaze and the blue color beneath the glaze. The lidded jar is a masterpiece among the polychrome (wuchi) porcelain wares with underglazed blue color made in the official kilns of the Jiajing reign. ", url:"    ./img/42.png    "},
                {index: 43 ,kind:  1 ,kindex: 30 ,color:"#3C4B83"  , name:"    Polychrome Loop-handled Pot with Designs of a Lotus Pond and Mandarin Ducks ", period:" Wanli reign (1573-1620), Ming dynasty (1368-1644)       ", type:"   colorful        ", kiln:"   Jingdezhen kilns    ", intro:"  This loop-handled pot was a teapot in the imperial court during the Wanli reign. Mandarin ducks in a lotus pond are painted on the stomach. ", url:"    ./img/43.png    "},
                {index: 44 ,kind:   1,kindex: 33 ,color:"#DDE2D3"  , name:"    Urn-shaped Cup with Chicken Design in Contrasting Colors    ", period:" Chenghua reign (1465-1487), Ming dynasty (1368-1644)        ", type:"     colorful      ", kiln:"   Jingdezhen kilns    ", intro:"  The cup has a slightly flaring mouth, a tapering body and a concave foot. The polychrome design depicts hens and their babies pecking in a garden. From the Chinese rose and orchids growing around the garden rocks, we know that the time is early spring. No glaze was applied around the concave foot. At the center of the foot, the mark 'Made in Chenghua reign of the Great Ming'(Da Ming Chenghua nian zhi) was inscribed in two vertical lines.   The cup is noted for its squared-off contour, lovely decoration, and translucent thinness. The application of contrasting colors follows the style of Huang Quan (ca. 903-965), a court painter in the Five dynasties (906-960).   The cup was made in the imperial kiln in the 'ceramic capital' Jingdezhen in southeastern China's Jiangxi province. According to historical documents, it was made as one of a pair. Its unique shape made it a masterpiece of the Chenghua reign. Admiration for the cups inspired reproductions in subsequent centuries including today. In the Qing dynasty (1644-1911), those made during the Kangxi reign (1662-1722) were virtually identical.   ", url:"    ./img/44.png    "},
                {index: 45 ,kind:  3 ,kindex: 4 ,color:"#96AB87"  , name:"    Covered Jar with Yellow Design of Dragon and Clouds on a Green Ground   ", period:" Wanli reign (1573-1620), Ming dynasty (1368-1644)       ", type:"     colorful      ", kiln:"   Jingdezhen kilns    ", intro:"  The motifs were all carved on the unglazed biscuit before craftsmen glazed and fired the jar at low temperatures. Within the diamond shaped panels around the stomach are motifs of dragon among clouds. The eight Buddhist emblems decorate the jar above and below the panels. Dragon among clouds typifies the decoration of Qing court items, demonstrating the imperial dignity.   ", url:"    ./img/45.png    "},
                {index: 46 ,kind:  1 ,kindex: 35 ,color:"#72310C"  , name:"    Monk's Cap Jug with Bright Red Glaze    ", period:" Xuande reign (1426-1435), Ming dynasty (1368-1644)      ", type:"  red glaze         ", kiln:"   Jingdezhen kilns    ", intro:"  The pot got its name for its resemblance to monk's cap at the mouth rim. It was made after the metal vessel used in Tibetan Buddhism. The glaze contains copper to present the red color in a reducing atmosphere at high temperatures. It is quite difficult to achieve a smooth, lustrous effect because very strict conditions are required during firing. This is a masterpiece of the Zhengde reign.   ", url:"    ./img/46.png    "},
                {index: 47 ,kind:  4 ,kindex:  2,color:"#C7C4BC"  , name:"    White-glazed Statuette of Seated Avalokiteśvaras    ", period:" Ming dynasty (1368-1644)        ", type:"   white glaze         ", kiln:"   Dehua kilns     ", intro:"  The Goddess of Mercy with plump and smooth-skinned oval face and benevolent expression lowers her head and eyes and seems to be watching all living creatures in the world. She wears high coiffeur decorated in the middle with ruyi-shaped head ornament, hood, long shawl and ruyi-shaped necklace and pendant. Her hands are hidden in the clothes while one leg is half revealed and the other is crossed. Through the drooping and undulating drapes, the Goddess's bearing is dimly visible. The statue is glazed white and hollow inside; its back is inscribed with the three-character seal mark of 'He Chao Zong' in intaglio. White porcelain of the Ming Dehua kiln pursued perfect jade quality and developed its own school. This statue is a masterpiece of the Ming porcelain master He Chaozong, whose artistic achievement represents Dehua kiln's high level.   ", url:"    ./img/47.png    "},
                {index: 48  ,kind: 1 ,kindex:  11,color:"#616C91"  , name:"    Goose-shaped Vase with Sky-blue Glaze   ", period:" Ming dynasty (1368-1644)        ", type:"   sky-blue glaze      ", kiln:"   Yixing kilns    ", intro:"  Yixing Kiln is located in Yixing, Jiangsu province. Made in Yixing kilns in imitations of the Jun wares of the Song dynasty (960-1279), Yijun wares are actually sky-blue glazed zisha vessels. With sky-blue glaze and tiny crackles on the surface, this vase has a goose-shaped spout with the opening on the gooseneck. ", url:"    ./img/48.png    "},
                {index: 49  ,kind: 2 ,kindex: 9 ,color:"#B0BABA"  , name:"    Celadon Zun Vessel in the Style of Pomegranate  ", period:" Ming dynasty (1368-1644)        ", type:"   celadon         ", kiln:"   Longquan kilns  ", intro:"  The Longquan kiln complex is located in Longquan city, Zhejiang province. Starting porcelain manufacture in the Northern Song dynasty (960-1127), Longquan kilns are famous for celadon wares. Coated in translucent greenish tint glaze, the zun vessel displayed here is designed after a pomegranate, and is carved with various kinds of interlocking floral motifs on the exterior wall. It is a masterpiece among the extant Longquan wares.  ", url:"    ./img/49.png    "},
                {index: 50  ,kind: 3 ,kindex: 9 ,color:"#818296"  , name:"    Polychrome Beaker Vase with Design of Peony and Magnolia    ", period:"  Shunzhi reign (1644-1661), Qing dynasty (1644-1911)        ", type:"  colorful         ", kiln:"   Jingdezhen kilns    ", intro:"  In the Qing dynasty Shunzhi era, polychrome porcelain shapes retained the antique flavor of late Ming dynasty. Many vessels employed a strong contrast between vivid hues of vermillion and green boldly painted in unrestrained fashion. The body of this beaker vase (gu) has white glaze with blue-green specks, polychrome-painted with distinct images of irregular rocks, flowers, and other designs. Each color is vibrant, with visual effects presented clearly with a refined sense of beauty.    ", url:"    ./img/50.png    "},
                {index: 51  ,kind: 3 ,kindex: 2 ,color:"#253656"  , name:"    Blue-and-white Prunus Vase with the Design of Birds Perching on a Withered Tree ", period:" Yongzheng reign (1723-1735), Qing dynasty (1644-1911)       ", type:"   blue-and-white      ", kiln:"   Jingdezhen kilns    ", intro:"  This slender neck of this vessel takes its name from resemblance to the thin branches of a plum tree. The interior is glazed white while the exterior is decorated with blue painting of sparrows perching face-to-face on wintery tree branches. The design is sparse and elegant while the painting is lifelike and natural.  ", url:"    ./img/51.png    "},
                {index: 52  ,kind: 3 ,kindex: 7 ,color:"#3A488E"  , name:"    Blue-and-white Vase with Hornless Dragon Shaped Ears and the Design of Dragon among Clouds  ", period:" Jiaqing reign (1796-1820), Qing dynasty (1644-1911)         ", type:"     blue-and-white         ", kiln:"   Jingdezhen kilns    ", intro:"  Symmetrical dragon ears adorn either side of the neck of this vase. The interior has white glaze while the exterior is painted with floral clouds and a dragon design. The strong and ferocious dragon emerges through the fiery clouds hovering above the ocean. The brushwork is fine and fluid. The composition shifts from ornate to simple, which is typical of the ornamental style of the Qianlong to Jiaqing transitional era.  ", url:"    ./img/52.png    "},
                {index: 53  ,kind:  2,kindex: 12 ,color:"#645A94"  , name:"    Brush Holder with Landscape Design in Three Underglazed Colors  ", period:" Kangxi reign (1662-1722), Qing dynasty (1644-1911)      ", type:"    colorful       ", kiln:"   Jingdezhen kilns    ", intro:"  This type of tricolor glaze was specific to the Kangxi era. Apart from the underglaze red and cobalt blue that are commonly seen, bean-green is added to intensify the image. The combination creates a beautiful multicolored effect.  ", url:"    ./img/53.png    "},
                {index: 54  ,kind: 2 ,kindex: 11 ,color:"#587C87"  , name:"    Flowerpot with Chestnut-flower Shaped Mouth and Designs of Landscape and Figure in Contrasting Colors   ", period:" Kangxi reign (1662-1722), Qing dynasty (1644-1911)      ", type:"  colorful         ", kiln:"   Jingdezhen kilns    ", intro:"  This six-sided flowerpot is decorated with paintings of pomegranates along its bottom edges with the character for 'longevity' (shou) painted in between. The six faces all bear images that celebrate longevity. The figures are vivid and life-like; the brushwork is exquisite. This work is a fine example of Kangxi era large-sized polychrome porcelain.  ", url:"    ./img/54.png    "},
                {index: 55  ,kind: 2 ,kindex: 2 ,color:"#855B4C"  , name:"    Vase with a Straight Neck and Design of Dragon among Clouds in Iron-red and Gold    ", period:" Kangxi reign (1662-1722), Qing dynasty (1644-1911)      ", type:"   Red glaze       ", kiln:"   Jingdezhen kilns    ", intro:"  Porcelain such as this vase, decorated in red and gold, was in vogue during the Kangxi era. Its interior and exterior are glazed white with red and gold painting on the exterior. Dragons in clouds chase a flaming pearl. The foot and mouth are decorated with matching lotus-flower pattern that constrasts to the ferociousness of the dragons.    ", url:"    ./img/55.png    "},
                {index: 56  ,kind:  2,kindex:  7,color:"#657260"  , name:"    Plain Tricolor Incense Burner with Openwork ", period:" Kangxi reign (1662-1722), Qing dynasty (1644-1911)      ", type:"    colorful       ", kiln:"   Jingdezhen kilns    ", intro:"  Seen from above, this octagonal-shaped incense burner shows the Buddhist swastika (卍) mark in the interior bottom. The body is glazed green with black specks while side pillars are decorated with a hornless dragon. The composition predominately uses yellow, green, and purple, with blue as supplement. The glaze colors are simple but elegant. This work examplifies court porcelain ware that combined beauty and untility.    ", url:"    ./img/56.png    "},
                {index: 57  ,kind: 1 ,kindex: 34 ,color:"#D1B525"  , name:"    Bowl with Flower Designs on a Yellow Ground in Enamels  ", period:" Kangxi Reign (1662-1722), Qing Dynasty (1644-1911)      ", type:"   yellow glaze        ", kiln:"   Jingdezhen kilns    ", intro:"  The interior of the bowl is unadorned while the exterior bears yellow glaze and enamel decorations of green pine trees and rocks with a peony and chrysanthemum pattern. The design is neat and exquisite while the colors are bright and eye-catching. Enamel porcelain was produced exclusively for court use. Only a small quantity was made and passed down through the generations.    ", url:"    ./img/57.png    "},
                {index: 58  ,kind: 3 ,kindex: 5 ,color:"#C6B083"  , name:"    Vase with Elephant-shaped Ears and Lotus Design in Enamels  ", period:" Qianlong Reign (1736-1795), Qing Dynasty (1644-1911)        ", type:"     colorful      ", kiln:"   Jingdezhen kilns    ", intro:"  Late Qianlong-era enamel arts frequently have a ground of floral motifs that imitate metalwork. While the interior of the vase is glazed green, its exterior is decorated with gold linework. Symmetrical elephant ear-shape handles adorn either side of the vessel. A rosette pattern covers a ground of white and gold floral pattern with a luxurious and splendid effect.  ", url:"    ./img/58.png    "},
                {index: 59  ,kind: 2 ,kindex: 15 ,color:"#BEB65A"  , name:"    Elephant-handled Famille-rose Vase with Revolving Interior and Chinese Characters for Recording Years and Days on a Yellow Ground   ", period:" Qianlong reign (1736-1795), Qing dynasty (1644-1911)        ", type:"   yellow glaze      ", kiln:"   Jingdezhen kilns    ", intro:"  The vase has a reticulated exterior and an independently revolving interior. A small vase is set inside, the neck of which links with the exterior so it can rotate. The small vase has famille rose against white glaze. The shoulder of the larger vase have twenty-four framed roundels containing names of Heavenly Stems (tian gan) and Earthly Branches (di zhi) in seal script (zhuan shu), as well as two words in regular script (kai shu) reading 'jia zi' (the first year of the sixty-year cycle) and 'ten thousand years' (wan nian). They are part of the sixty-year cycle calendar calculated in the traditional way. The belly is decorated with yellow glaze, flowers and interlocking branches. On it are four windows displaying each season opening to the interior vase which has paintings of children (see details). People could turn the interior vase and see many children at play in different seasons. On the bottom is the blue-and-white reign mark in archaic seal script (zhuan shu).  Since the three parts of the vase were fired separately, craftsmen had to seriously control temperatures to ensure these parts could be integrated. The vase with revolving interior was a new type of porcelain ornament innovated after the eighth year of the Qianlong reign (1743).   ", url:"    ./img/59.png    "},
                {index: 60  ,kind:1,kindex: 32 ,color:"#6C4246"  , name:"    Chrysanthemum Petal Shaped Zisha Teapot ", period:" Qianlong reign (1736-1795), Qing dynasty (1644-1911)        ", type:"    purple        ", kiln:"   Yixing kiln     ", intro:"  Yixing kiln is located in Yixing, Jiangsu province The unique form of this teapot is modeled after the radial symmetry of flowers. The characters 'Made by Chen Yingshang zhi' are carved in relief in the bottom of the teapot. Chen Yingshang was a famous early-Qing teapot maker.   ", url:"    ./img/60.png    "},
                {index: 61  ,kind:2  ,kindex:  1,color:"#A74233"  , name:"    Peach-bloom Radish-shaped Zun Vessel    ", period:" Kangxi reign (1662-1722), Qing dynasty (1644-1911)      ", type:"  Red glaze          ", kiln:"   Jingdezhen kilns    ", intro:"  This zun takes its name from its resemblance to a radish. Late Kangxi-era peach-bloom red glaze, produced at Jingdezhen, is a kind of high-temperature copper red glaze that is named for its resemblance to the color of the peach blossom. The luminous red glaze is otherwise known as 'cowpea skin red', 'baby's cheek', and 'tipsy beauty'. The glaze just under the neck is thin and transparent, thereby revealing the color of the clay body.   ", url:"    ./img/61.png    "},
                {index: 62  ,kind: 2 ,kindex: 3 ,color:"#88182C"  , name:"    Red-glazed Lute-shaped Zun Vessel   ", period:" Kangxi reign (1662-1722), Qing dynasty (1644-1911)      ", type:"   Red glaze       ", kiln:"   Jingdezhen kilns    ", intro:"  The vase has a reticulated exterior and an independently revolving interior. A small vase is set inside, the neck of which links with the exterior so it can rotate. The small vase has famille rose against white glaze.   ", url:"    ./img/62.png    "},
                {index: 63  ,kind: 2 ,kindex: 5 ,color:"#EBEBEB"  , name:"    White-glazed Gall-bladder Vase with Incised Decoration  ", period:" Qing dynasty (1644-1911)        ", type:"  white glaze         ", kiln:"   Dehua kilns     ", intro:"  The shoulder of the larger vase have twenty-four framed roundels containing names of Heavenly Stems (tian gan) and Earthly Branches (di zhi) in seal script (zhuan shu), as well as two words in regular script (kai shu) reading 'jia zi' (the first year of the sixty-year cycle) and 'ten thousand years' (wan nian). They are part of the sixty-year cycle calendar calculated in the traditional way. The belly is decorated with yellow glaze, flowers and interlocking branches. On it are four windows displaying each season opening to the interior vase which has paintings of children (see details). People could turn the interior vase and see many children at play in different seasons. On the bottom is the blue-and-white reign mark in archaic seal script (zhuan shu).    ", url:"    ./img/63.png    "},
                {index: 64  ,kind:1,kindex: 26 ,color:"#C09F83"  , name:"    Zisha Teapot with a Tri-handle  ", period:" Qing dynasty (1644-1911)        ", type:"   purple        ", kiln:"   Yixing Kilns    ", intro:"  The teapot has a round body, a swelling stomach and a flat bottom. Above the cover is a loop-shaped tri-handle, tactfully bowing in a natural way. The round lid slightly bulges with a knob imitating a Taihu stone. The yellow clay is close-textured. The handle fits into the body so well that the teapot is characterized by liveliness and artistic balance. After the mid Qing dynasty most of the single loop-handled teapots were changed to double-handled which have greater stability and artistry.   ", url:"    ./img/64.png    "},
                {index: 65 ,kind:  3 ,kindex:  3,color:"#638F9C"  , name:"    Large Vase Decorated with a Picture of 'Imperial Porcelain Workshop” in Famille Rose    ", period:" Daoguang reign (1821-1850), Qing dynasty (1644-1911)        ", type:"    colorful       ", kiln:"   Jingdezhen kilns    ", intro:"  This multicolor famille rose vase depicts sixty-one craftsmen at work in the imperial kilns at Zhushan of Jingdezhen. The image documents the organizational system, division of labor, and manufacturing process at the kiln. This vessel serves as a primary document for research on imperial kilns. ", url:"    ./img/65.png    "},
                {index: 66 ,kind:  1 ,kindex: 27 ,color:"#292E2B"  , name:"    Melon-shaped Ewer with Beast Design in Polychrome   ", period:" Kangxi reign (1662-1722), Qing dynasty (1644-1911)      ", type:"     yellow glaze      ", kiln:"   Jingdezhen kilns    ", intro:"  The teapot has a polychrome painting of an auspicious qilin unicon accompanied by flowers and rocks. The uniquely shaped teapot is enhanced by the painting's rich colors and full composition. This work is donated by Volvo China.    ", url:"    ./img/66.png    "},
                {index: 67 ,kind: 3  ,kindex: 11 ,color:"#7BB9B6"  , name:"    Citron Plate in the Form of a Lotus Leaf    ", period:" Qianlong reign (1736-1795), Qing dynasty (1644-1911)        ", type:"    green glaze     ", kiln:"   Jingdezhen kilns    ", intro:"  Porcelain with famille roseThe lotus-leaf-shaped plate has curved edges and feet in design of a red water nut and a blue river snail. On one side, a stem leans on the surface of the leaf. The rim of the plate is attached with a lotus and a seedpod of lotus holding movable seeds. The bottom bears a blue-and-white four-character Qianlong reign mark.   The so-called 'citron plate' is a small fruit plate placed in the scholar's studio. It usually holds perfumed fruit including yellow citrons and 'Buddha hand' fruit. The plate with fruit could not only provide a pleasant scent to the atmosphere but also add interest to the scholar's life. This citron plate successfully captures the colors and shapes of natural things, exemplifying the sophistication of the porcelain production in the Qianlong reign. ", url:"    ./img/67.png    "}

            ];

        
        //for (var i = 0; i < 4; i++) {
        // for (var j = 0; j < 3; j++) {
        // items[i].lists.push(i + '-' + j);
        // }
        // }
        return {
            all: function () {
                return items;
            },
            remove: function (item) {
                items.splice(items.indexOf(item), 1);
            },
            indexOf: function (item) {
                return items.indexOf(item);
            },
            get: function (itemId) {
                for (var i = 0; i < items.length; i++) {
                    if (items[i].index === parseInt(itemId)) {
                        return items[i];
                    }
                }
                return null;
            },
            getkind: function (kind) {
                var newitems=[];
                for (var i = 0; i < items.length; i++) {
                    if (items[i].kind === parseInt(kind)) {
                        newitems.push(items[i]);
                    }
                }
                return newitems;
                // return null;
            }
        };

    })
